name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get changed folders
      id: get-changed-folders
      run: |
        changed_folders=$(git diff --name-only HEAD^ HEAD | grep 'Dockerfile' | sed 's|/[^/]*$||' | sort -u)
        echo "::set-output name=changed_folders::$changed_folders"

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Images
      run: |
        changed_folders="${{ steps.get-changed-folders.outputs.changed_folders }}"
        for folder in $changed_folders; do
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$folder:latest $folder
          docker push ${{ secrets.DOCKER_USERNAME }}/$folder:latest
        done
