name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get changed folders
      id: get-changed-folders
      run: |
        if git rev-parse --verify HEAD~1; then
          changed_folders=$(git diff --name-only HEAD~1 HEAD | grep 'Dockerfile' | sed 's|/[^/]*$||' | sort -u)
        else
          changed_folders=$(git ls-tree --name-only -r HEAD | grep 'Dockerfile' | xargs -n 1 dirname | sort -u)
        fi
        echo "::set-output name=changed_folders::$changed_folders"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Images
      run: |
        changed_folders="${{ steps.get-changed-folders.outputs.changed_folders }}"
        for folder in $changed_folders; do
          # Generate a build number based on the current date and time
          build_number=$(date '+%Y%m%d%H%M%S')
          
          # Build the Docker image with the generated build number as a tag
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$folder:$build_number $folder
          
          # Push the Docker image with the generated build number as a tag
          docker push ${{ secrets.DOCKER_USERNAME }}/$folder:$build_number
        done
