name: Build and Push Multi-Arch Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-latest-arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Get changed folders
        id: get-changed-folders
        run: |
          if git rev-parse --verify HEAD~1; then
            changed_folders=$(git diff --name-only HEAD~1 HEAD | grep 'Dockerfile' | sed 's|/[^/]*$||' | sort -u)
          else
            changed_folders=$(git ls-tree --name-only -r HEAD | grep 'Dockerfile' | xargs -n 1 dirname | sort -u)
          fi
          echo "changed_folders=${changed_folders}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          changed_folders="${changed_folders}"
          for folder in $changed_folders; do
            # Generate a build number based on the current date and time
            build_number=$(date '+%Y%m%d%H%M%S')

            # Replace '/' characters in folder names with '-'
            folder_name="${folder//\//-}"

            # Replace '/' characters in folder names with '_' for image reference
            image_reference="${folder_name//\//-}_$build_number"

            # Build the Docker image for amd64
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$image_reference $folder

            # Build the Docker image for arm64
            docker build -t ${{ secrets.DOCKER_USERNAME }}/${image_reference}_arm64 $folder --build-arg ARCH=arm64
            
            # Push the Docker image with the generated build number as a tag
            docker push ${{ secrets.DOCKER_USERNAME }}/$image_reference
            docker push ${{ secrets.DOCKER_USERNAME }}/${image_reference}_arm64
          done

      - name: Create Docker Manifest
        run: |
          changed_folders="${changed_folders}"
          for folder in $changed_folders; do
            folder_name="${folder//\//-}"
            image_reference="${folder_name//\//-}_$build_number"
            docker manifest create ${{ secrets.DOCKER_USERNAME }}/$image_reference ${{ secrets.DOCKER_USERNAME }}/$image_reference ${{ secrets.DOCKER_USERNAME }}/${image_reference}_arm64
            docker manifest annotate ${{ secrets.DOCKER_USERNAME }}/$image_reference ${{ secrets.DOCKER_USERNAME }}/${image_reference}_arm64 --os linux --arch arm64
            docker manifest push ${{ secrets.DOCKER_USERNAME }}/$image_reference
          done
        if: always()
